filename = input('Enter file name>>')
try:
    fhandler = open(filename)
    md = input('Press R to read, W to write, A to append, K to rep \n>> ')
    if md == 'R' or md == 'r':
        # fhandler = open(filename,'r')
        ftext = fhandler.read()
        print('File Name>>',filename,'\n\n',ftext)
    elif md == 'W' or md == 'w':
        fhandler = open(filename, 'r')
        ftext = fhandler.read()
        print('Existing file info:')
        print('File Name>>',filename,'\n\n',ftext)
        fhandler = open(filename, 'w')
        temptxt = input('Enter text to be added to file\n>>')
        fhandler.write(temptxt)
        fhandler = open(filename)
        ftext = fhandler.read()
        print('New file info:')
        print('File Name>>',filename,'\n\n',ftext)
    elif md == 'A' or md == 'a':
        fhandler = open(filename, 'r')
        ftext = fhandler.read()
        print('Existing file info:')
        print('File Name>>',filename,'\n\n',ftext)
        fhandler = open(filename,'a')
        temptxt = input('Enter text to be added to file\n>>')
        fhandler.write('\n')
        fhandler.write(temptxt)
        fhandler = open(filename)
        ftext = fhandler.read()
        print('Appended file info:')
        print('File Name>>',filename,'\n\n',ftext)
    elif md == 'K' or md == 'k':
        fhandler = open(filename,'r')
        ftext = fhandler.read()
        print('Existing file info:')
        print('File Name>>',filename,'\n\n',ftext)
        fhandler.close()
        lno = int(input('Enter line no.'))
        fhandler = open(filename,'r')
        temptxt = input('Enter text>>')
        templines = fhandler.readlines()
        print(templines)
        fhandler.close()
        templines[lno-1] = temptxt+'\n'
        fhandler = open(filename,'w')
        fhandler.writelines(templines)
        fhandler.close()
        fhandler = open(filename)
        ftext = fhandler.read()
        print(ftext)
        print('Changes Done!\nLine', lno, 'changed to>>',temptxt)
    else: print('Bad input')
except:
    fhandler = open(filename,'w')
    temptxt = input('Enter text to be added to file\n>>')
    fhandler.write(temptxt)
    fhandler = open(filename)
    ftext = fhandler.read()
    print('New file info:')
    print('File Name>>',filename,'\n\n',ftext)

fhandler.close()
